# Generated by Django 3.2.13 on 2022-09-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
