# Generated by Django 3.2.13 on 2022-09-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_recipes', '0002_profile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categoryOf', to='simple_recipes.Category'),
        ),
    ]
