# Generated by Django 3.2.13 on 2022-09-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_recipes', '0006_articlecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
