# Generated by Django 3.2.13 on 2022-09-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_recipes', '0008_alter_articlecomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
    ]
